### ISSUE TITLE
Refactor exception messages

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Schedule-RTU#13]
Для понимания ситуации данные  логи никак не подходят, необходимо описать информативные сообщения. Желательно на английском.

https://github.com/RTUITLab/Schedule-RTU/blob/15b4734ab29986c4eab97764fd1968bea9e61db3/schedule_parser/main.py#L27
https://github.com/RTUITLab/Schedule-RTU/blob/15b4734ab29986c4eab97764fd1968bea9e61db3/schedule_parser/main.py#L34

**Comment by Nekolya** [comment]
[Исправлено](https://github.com/RTUITLab/Schedule-RTU/commit/0d31a04b81e218cbe93561fe811f3bb1a0f59bad)
