### ISSUE TITLE
lesson 5, 11 week

### ISSUE THREAD

**Issue by Delivery-Klad** [RTUITLab/Schedule-RTU#14]
![image](https://user-images.githubusercontent.com/49003989/109317276-9a3e5500-785d-11eb-8518-8eddd982c07c.png)

**Comment by Delivery-Klad** [comment]
запрос today неделя 3

**Comment by Nekolya** [comment]
[Исправлено](https://github.com/RTUITLab/Schedule-RTU/commit/0d31a04b81e218cbe93561fe811f3bb1a0f59bad)
