### ISSUE TITLE
Production docker file

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Schedule-RTU#3]
Необходимо сделать корректный docker file, который поднимает не development сервер, а правильный, через мануалы по flask или подобным статьям. Например, можно использовать данный базовый образ https://hub.docker.com/r/tiangolo/meinheld-gunicorn-flask/
![image](https://user-images.githubusercontent.com/12235437/107227759-a5c1fd00-69d0-11eb-9005-01e5f8513854.png)

**Comment by Nekolya** [comment]
[Решено](https://github.com/RTUITLab/Schedule-RTU/commit/833ad2a3aaa3d5f0f772e7f815c4b52bd1e0eaeb)
