### ISSUE TITLE
Api documentation

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Schedule-RTU#4]
Необходимо описать в каком-то виде api, каке запросы есть, какие можно слать, и что ожидать в ответ.

Лучший вариант - автогенерируемая openapi документация (swagger). Если запросов мало - можно вынести в отдельынй markdown файл и поддерживать в актуальном состоянии самостоятельно

**Comment by Nekolya** [comment]
Сделано [тут](https://github.com/RTUITLab/Schedule-RTU/commit/c29bbaa1cb3d886487f346aae6e1434f2af9ee85) и [тут](https://github.com/RTUITLab/Schedule-RTU/commit/376483d541f891589b406b89fa867acfa28bc42b)
