### ISSUE TITLE
handle empty database

### ISSUE THREAD

**Issue by CAPCHIK** [RTUITLab/Schedule-RTU#9]
Сейчас если запрашивать расписание при пустой БД происходит парсинг сайта mirea, необходимо сделать так, чтобы парсинг сайте никак не был связан с GET запросами от клиентов.

При отсутствующей БД можно возвращать 503 статус с заголовоком [Retry-After](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Retry-After) с значением в пару минут.

Возможность возврата такого кода необходимо отразить в swagger в документации.

**Comment by Nekolya** [comment]
[Сделано](https://github.com/RTUITLab/Schedule-RTU/commit/88470249b981b1ed080333c1b085c38afcf3dc17)
